config/routes.rb
Rails.application.routes.draw do
root 'boards#index'

  devise_for :users

  resources :boards do
    resources :lists
  end

  resources :lists do
    resources :tasks
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy

  def self.all_boards(user_id)
    Board.find_by_sql("
    SELECT *
    FROM boards AS b
    WHERE b.user_id = #{user_id}
    ")
  end

  def self.find_board(user_id, board_id)
    Board.find_by_sql(["
    SELECT *
    FROM boards AS b
    WHERE b.user_id = ? AND b.id = ?
    ", user_id, board_id]).first
  end
  
  def self.select_focus_point_New_List
    if List.all.count == 0
      return true
    else
      return false
    end
  end

  def self.select_focus_point_New_Task
    if List.all.count == 1
      return true
    else
      return false
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy

  def self.all_lists(board_id)
    List.find_by_sql("
    SELECT *
    FROM lists AS l
    WHERE l.board_id = #{board_id}
    ")
  end

  def self.find_list(board_id, list_id)
    List.find_by_sql(["
    SELECT *
    FROM lists AS l
    WHERE l.board_id = ? AND l.id = ?
    ", board_id, list_id]).first
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  def self.all_tasks(list_id)
    Task.find_by_sql("
    SELECT *
    FROM tasks AS t
    WHERE t.list_id = #{list_id}
    ")
  end

  def self.find_task(list_id, task_id)
    Task.find_by_sql(["
    SELECT *
    FROM tasks AS t
    WHERE t.list_id = ? AND t.id = ?
    ", list_id, task_id]).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_boards

  def set_boards
  @boards = current_user ? current_user.boards : []
  end


end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
before_action :set_board, only: [:show, :edit, :update, :destroy]
before_action :set_lists
before_action :set_tasks

  def index
    @boards = Board.all_boards(current_user.id)
    if @boards.first != nil
      redirect_to board_path(@boards.first)
    end
  end

  def new
    @board = Board.new
    render "form"
  end

  def create
    @board = current_user.boards.new(board_params)
    if @board.save
    redirect_to boards_path
    else
      render "form"
    end   
  end

  def edit
    render "form"
  end

  def update
    if @board.update(board_params)
    redirect_to board_path(@board)
    else
    render "form"
    end
  end

  def show
    @focus_list = Board.select_focus_point_New_List
    @focus_task = Board.select_focus_point_New_Task
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private
  
    def board_params
      params.require(:board).permit(:name)
    end

    def set_board
      #@board = current_user.boards.find(params[:id])
      @board = Board.find_board(current_user.id, params[:id])
    end

    def set_lists
      @lists = @board ? @board.lists : []
      @lists = @lists.each { |l| 
        if l.priority == nil
        l.priority = 0
        end }
      @lists = @lists.sort_by { |l| l.priority }
    end

    def set_tasks
      @tasks = @list ? @list.tasks : []
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
before_action :set_board
before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all_lists(@board.id)
    #@lists = @board.lists
  end

  def new
    @list = @board.lists.new
    render '/layouts/_list_form'
  end

  def create
    @list = @board.lists.new(list_params)
    if @list.save
      redirect_to board_path(@board)
    else
      render '/layouts/_list_form'
    end
  end
  
  def edit
    render '/layouts/_list_form'
  end
  
  def update
    if @list.update(list_params)
      redirect_to board_path(@board)
    else
      render '/layouts/_list_form'
    end
  end

  def show
  end

  def destroy
    @list.destroy
    redirect_to board_path(@board)
  end
  
  private
  
  def list_params
    params.require(:list).permit(:name, :priority, :board_id)
  end
  
  def set_list
    @list = List.find_list(@board.id, params[:id])
    #@list = List.find(params[:id])
  end
  
  def set_board
    @board = current_user.boards.find(params[:board_id])
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, only: [:edit, :update, :show, :destroy]
  before_action :set_board

  def index
    @tasks = Task.all_tasks(@list.id)
    #@tasks = @list.tasks
  end

  def new
    @task = Task.new
    render '_task_form'
  end

  def create
    @task =  @list.tasks.new(task_params)
    if @task.save
      redirect_to board_path(@board)
    else
      render '_task_form'
    end
  end


  def edit
    render '_task_form'
  end

  def update
    if @task.update(task_params)
    redirect_to board_path(@board)
    else
    render 'task_form'
    end 
  end


  def show
  end

  def destroy
    @task.destroy
    redirect_to board_path(@board)
  end


  private
  def task_params
    params.require(:task).permit(:name, :description, :list_id)
  end
  
  def set_list
    @list = list.find(params[:list_id])
  end  

  def set_task
    @task = Task.find_task(@list.id, params[:id])
    #@task = Task.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_board
    @board = @list.board
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/form.html.erb
<h1><%= @board.name ? "Edit " : "New " %>Board</h1>
<br />
<br />
<div class="form_input"><%= form_with(model: @board, local: true) do |f| %><?div>
<div class="form_input"><%= f.text_field :name, autofocus: true, style: "text-align: center; width: 300px; font-size: 2em; font-style: bold;" %></div>
<br />
<div class="form_input" style="text-align: center;"><%= f.submit %></div>
<% end %>
</hr>

app/views/boards/index.html.erb
<h1>Welcome to Trollo</h1>
<h3>Create a board to get started!</h3>

app/views/boards/show.html.erb
<div id="board-container">
  <div id="board-title-container">
    <h1>
      <%= link_to "#{@board.name}", edit_board_path(@board), method: :get, class: "text_link", style: "font-size: 2em; font-style: bold;" %></a>
      <%= link_to image_tag("trashcan.png", alt: "x", class: "trashcan"), board_path(@board), method: :delete, data: {confirm: "Delete Entire Board?"}, class: "text_link", title: "Delete" %>
    </h1>
  </div>
  <br />
  <%= button_to "New List", new_board_list_path(@board), method: :get, style: "border-radius: 5px; border-width: 3px;", autofocus: @focus_list; %>
  <%= render "/lists/index" %>
</div>

app/views/layouts/_list_form.html.erb
<h1><%= @list.name ? "Edit " : "New " %>List</h1>
<div class="form_input"><%= form_with(model: [@board, @list], local: true) do |f| %><?div>
<br />
<div class="form_input" style="text-align: center;"><%= f.text_field :name, autofocus: true, style: "text-align: center; font-size: 1.5em;" %></div>
<div class="form_input_label" style="text-align: center"><%= f.label :priority %></div>
<div class="form_input" style="text-align: center;"><%= f.text_field :priority, placeholder: "0", style: "text-align: center; width: 20%"  %></div>
<div class="form_input" style="text-align: center;"><%= f.submit %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<div style="width: 100vw">
  <div class="navbar">
    <div class="nav-item" id="logo-container" >
      <h1 id="logo" style="color: white; margin: 0;">Trollo</h1>
    </div>
    <% @boards.each do |board| %>
    <a><%= link_to board.name, board_path(board), class: "nav-item" %></a>
    <% end %>
    <a><%= link_to "+", new_board_path, class: 'nav-item' %></a>
    <a class="nav-item-empty"></a>
    <div class="nav-item" id="user-sign-in" >
      <% if user_signed_in? %>
        <%= link_to current_user.email, edit_user_registration_path, class: "user-links" %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "user-links" %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %>
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar', class: "navbar" %>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/_index.html.erb
<div id="lists-container">
  <% @lists.each do |l| %>
    <div class="list">
    <h2 style="text-align: center"><%= link_to "#{l.name}", edit_board_list_path(@board, l), class: "text_link" %>
    <a><%= link_to image_tag("trashcan.png", alt: "x", class: "trashcan", style: "height: 15px"), board_list_path(@board, l), method: :delete, class: "text_link", title: "Delete" %></a>
    <h4 style="margin-block-start: 0em; margin-block-end: 0em;"><%= button_to 'New Task', new_list_task_path(l), method: :get, style: "width:200px; border-radius: 5px; border-width: 3px;", autofocus: @focus_task; %></h4>
    </h2>
    <% l.tasks.each do |task| %>
      <div id="task-card">
        <div>
          <h3 style="margin-block-start: 0; margin-block-end: 0;">
            <%= link_to task.name, edit_list_task_path(l, task), class: "text_link" %>
            <%= link_to image_tag("trashcan.png", alt: "x", class: "trashcan", style: "height: 12px"), list_task_path(l, task), method: :delete, class: "text_link", title: "Delete" %>
          </h3>
        </div>
      <h5><%= link_to task.description, edit_list_task_path(l, task), class: "text_link" %></h5>
      </div>
    <% end %>
    </div>
  <% end %>
</div>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/tasks/_index.html.erb
<% @list.tasks.each do |task| %>
  <div style="border: solid green 2px; width: 200px;">
  <h3><%= task.name %></h3>
  <h5><%= task.description %></h5>
  </div>
<% end %>

app/views/tasks/_task_form.html.erb
<h1><%= @task.name ? "Edit " : "New " %>Task</h1>
<br >
  <%= form_with(model: [@list, @task], local: true, style: "margin: auto") do |f| %>
    <div class="form_input" style="text-align: center;"><%= f.text_field :name, autofocus: true, style: "text-align: center; font-style: bold" %></div>
    <div><%= f.text_area :description, id: "task-text-area" %> </div>
    <br />
    <div class="form_input" style="text-align: center"><%= f.submit %></div>
<% end %>
</hr>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>